name: universal_dockit
description: A Flutter plugin for viewing PDF, Word, Excel, PowerPoint, EPUB, CBZ, TXT, CSV, RTF, and OpenDocument files on Android and iOS.
version: 1.0.2
homepage: https://github.com/prathap021/universal_dockit
repository: https://github.com/prathap021/universal_dockit
issue_tracker: https://github.com/prathap021/universal_dockit/issues
documentation: https://github.com/prathap021/universal_dockit#readme
license: MIT
changelog: CHANGELOG.md

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - pdf-viewer
  - office
  - excel
  - powerpoint
  - epub

flutter:
  plugin:
    platforms:
      android:
        package: com.prathap021.universal_dockit
        pluginClass: UniversalDockitPlugin
      ios:
        pluginClass: UniversalDockitPlugin